### ISSUE TITLE
query server config

### ISSUE THREAD

**Issue by yvendruscolo** [apache/couchdb-helm#11]
Hello,

First of all, thank you for the work put here!

Upon inspecting parameters and values, I wasn't quite sure how to setup `local.ini` to include
```
[native_query_servers]
enable_erlang_query_server = true
```

could it be done via `couchdbConfig`, or is it not possible as of now?
If possible, could I get an example?

**Comment by willholley** [comment]
yes, you should be able to set this via:
```
couchdbConfig:
    native_query_servers:
        enable_erlang_query_server: true
```
