### ISSUE TITLE
couchdb pod is crashing with any relevant clue

### ISSUE THREAD

**Issue by veduboy** [apache/couchdb-helm#19]
**Describe the bug**
Hi, 

I am deploying the couchdb over IBM kubernetes cluster using the helm chart, all the things are fine except pod is crashing, I have tried to debug doesn't find any relevant clue

**Version of Helm and Kubernetes**:

**Helm Version **
Client: &version.Version{SemVer:"v2.14.3", 
Server: &version.Version{SemVer:"v2.14.3", 

K8s version 
_____________________________________________________________________________________________
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.8", 
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.12+IKS", ____________________________________________________________________________________________

**What happened**:

_________________________________________________________________________________________________

 node.kubernetes.io/unreachable:NoExecute for 600s
Events:
  Type     Reason     Age                  From                     Message
  ----     ------     ----                 ----                     -------
  Normal   Scheduled  22m                  default-scheduler        Successfully assigned default/testcouch-couchdb-0 to 
  Normal   Pulling    22m                  kubelet,   pulling image "busybox:latest"
  Normal   Pulled     22m                  kubelet,  Successfully pulled image "busybox:latest"
  Normal   Created    22m                  kubelet  Created container
  Normal   Started    22m                  kubelet,   Started container
  Normal   Pulled     21m (x4 over 22m)    kubelet,  Container image "couchdb:2.3.1" already present on machine
  Normal   Created    21m (x4 over 22m)    kubelet,  Created container
  Normal   Started    21m (x4 over 22m)    kubelet,   Started container
  Warning  BackOff    118s (x98 over 21m)  kubelet,  Back-off restarting failed container

______________________________________________________
https://cloud.ibm.com/kubernetes/helm/ibm-charts/couchdb
______________________________________________________

Regards,
Vedansh

**Comment by willholley** [comment]
@veduboy the chart https://cloud.ibm.com/kubernetes/helm/ibm-charts/couchdb is not maintained by the CouchDB community. You'll need to raise this with IBM instead.

The CouchDB community helm chart should work on IBM IKS and is available at https://hub.helm.sh/charts/couchdb/couchdb.

**Comment by veduboy** [comment]
@willholley 

I have tried https://hub.helm.sh/charts/couchdb/couchdb  chart as well get the same result.

**Comment by willholley** [comment]
@veduboy can you attach the logs from the couchdb container and the output of `kubectl describe`, scrubbing any passwords?

**Comment by raspitakesovertheworld** [comment]
I have just run into the same issue. This is from the logs of the pod and might help somebody else:
*************************************************************
ERROR: CouchDB 3.0+ will no longer run in "Admin Party"
       mode. You *MUST* specify an admin user and
       password, either via your own .ini file mapped
       into the container at /opt/couchdb/etc/local.ini
       or inside /opt/couchdb/etc/local.d, or with
       "-e COUCHDB_USER=admin -e COUCHDB_PASSWORD=password"
       to set it via "docker run".
*************************************************************
