### ISSUE TITLE
Feature Request: Helm chart for CouchDB version 3.0.0 and/or 3.1.0.

### ISSUE THREAD

**Issue by karok2m** [apache/couchdb-helm#35]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
I would like to have a Helm chart for CouchDB version `3.0.0` and/or `3.1.0`.

**Describe alternatives you've considered**
A naive alternative might be setting `image.tag` in values to `3.0.0` or `3.1.0`. But I do not expect that to work.

**Additional context**
I am new to CouchDB, so I am not familiar with differences between `2.x` and `3.x` versions. We are considering CouchDB for deployments to on-premise Kubernetes clusters where we need an alternative for managed document databases that we use in cloud.

**Comment by kocolosk** [comment]
Good idea. This ought to be quite straightforward, maybe even a trivial bump to the `values.yaml`

**Comment by karok2m** [comment]
@kocolosk, I will close this issue as your changes are merged into `master` branch.
