### ISSUE TITLE
setting annotation would fail the installation for chart version above 3.3.0

### ISSUE THREAD

**Issue by raohuaming** [apache/couchdb-helm#37]
**Describe the bug**
if settings annotations while installing couchdb using helm, it will fail for versions above 3.3.0.

**Version of Helm and Kubernetes**:
helm version(client/server): "v2.12.3"
k8s version(client/server): "v1.11.0+d4cacc0"

**What happened**:

 it will throw errors as below:

Error: render error in "couchdb/templates/statefulset.yaml": template: couchdb/templates/statefulset.yaml:23:28: executing "couchdb/templates/statefulset.yaml" at <include (print $.Tem...>: error calling include: template: couchdb/templates/_helpers.tpl:14:14: executing "couchdb.fullname" at <.Values.fullnameOver...>: can't evaluate field fullnameOverride in type interface {}

**What you expected to happen**:

It should install couchdb successfully.

**How to reproduce it** (as minimally and precisely as possible):
3.3.1-3.3.2 would fail:
helm install --debug --dry-run --set annotations.hello=world,couchdbConfig.couchdb.uuid=xxxxyyy couchdb/couchdb --version 3.3.3
helm install --debug --dry-run --set annotations.hello=world,couchdbConfig.couchdb.uuid=xxxxyyy couchdb/couchdb --version 3.3.2
helm install --debug --dry-run --set annotations.hello=world,couchdbConfig.couchdb.uuid=xxxxyyy couchdb/couchdb --version 3.3.1

3.3.0 succeed:
helm install --debug --dry-run --set annotations.hello=world,couchdbConfig.couchdb.uuid=xxxxyyy couchdb/couchdb --version 3.3.0

**Anything else we need to know**:

nope.

**Comment by willholley** [comment]
Thanks for the report @raohuaming - https://github.com/apache/couchdb-helm/pull/38 fixes this.

**Comment by KaelBaldwin** [comment]
Any update on this @willholley ? Looks like you are just waiting for a CR, can we poke someone? I'm running into this problem now as well.

Thank you for fixing this!
