### ISSUE TITLE
Configurable Ingress Path

### ISSUE THREAD

**Issue by arjun-1** [apache/couchdb-helm#4]
Currently, the ingress path is hardcoded to be `/`. It would be really great if the ingress path could become configurable in `values.yaml` :). This is the only hardcoded value preventing my team from using this chart directly (we use path based routing). Couchdb should work out of the box with a configurable ingress path, when used in conjunction with the Rewrite Annotation.

**Comment by willholley** [comment]
@arjun-1 are you able to submit a PR for the change that meets your requirements? That would be the most expedient way of getting it into the published chart.
