### ISSUE TITLE
Add podDisruptionBudget.enabled value

### ISSUE THREAD

**Issue by Miouge1** [apache/couchdb-helm#49]
**Is your feature request related to a problem? Please describe.**
When draining a Kubernetes node with `kubectl drain`, several couchdb pods are sometimes evicted at the same time, resulting in an unavailable couchdb cluster.

**Describe the solution you'd like**
Adding a `kind: PodDisruptionBudget` option to allow for drain to respect the disruption budget. For example waiting for the first evicted pod to be ready before evicting the next one.

**Describe alternatives you've considered**

**Additional context**
Smaller kubernetes clusters are more affected by this since there are more chances that 2 couchdb pods are scheduled on the same node.

Here is an example of values that this could be controlled with:
```yaml
podDisruptionBudget:
  enabled: false
  # minAvailable: 1
  maxUnavailable: 1
```

**Comment by clayvan** [comment]
Totally wild that nobody else has asked for this? Maybe everyone is just creating their own PDB for it like we are?
