### ISSUE TITLE
Gitlab Pages / Helm Repo broken

### ISSUE THREAD

**Issue by Nold360** [apache/couchdb-helm#67]
**Describe the bug**
The latest Chart in the chart repo is 3.3.4 & it seems the current index.yaml has been created 2020-07-20

See also: https://github.com/apache/couchdb-helm/deployments/activity_log?environment=github-pages

**What you expected to happen**:
Me want 3.6.0 :(

**How to reproduce it** (as minimally and precisely as possible):
404: https://apache.github.io/couchdb-helm/couchdb-3.6.0.tgz
https://apache.github.io/couchdb-helm/index.yaml

**Anything else we need to know**:

**Comment by kocolosk** [comment]
Hmm, thanks for pointing this out, I thought we fixed this in #60

**Comment by kocolosk** [comment]
Ah, seems we can't choose `main` as a deployment branch:

> The ghp_branch setting can ONLY be either master or gh-pages.

https://cwiki.apache.org/confluence/display/INFRA/Git+-+.asf.yaml+features#Git.asf.yamlfeatures-GitHubPages

**Comment by kocolosk** [comment]
Filed https://issues.apache.org/jira/browse/INFRA-22854 to see if we can get that functionality extended. If we can't I'll push the updates to master while we figure out a better long-term solution.

**Comment by iamwillbar** [comment]
@kocolosk if it would be possible to push the changes to master in the meantime that would be great (so I can consume the 3.6.1 image you just published 😄).

**Comment by kocolosk** [comment]
Yes, done. Will continue to debug the main-based deployments with ASF Infra but at least this gets the published charts up-to-date.
