### ISSUE TITLE
Support IngressClass

### ISSUE THREAD

**Issue by discostur** [apache/couchdb-helm#69]
Hi,

would it be possible to support setting a IngressClass?

Thanks
Regards,
Kilian

**Comment by discostur** [comment]
@kocolosk it seems that you have released a new version of the helm chart which should contain this merge / fix - but if i download the helm chart i cannot see the changes. 

I cannot see any merge in your master branch, too. Did there anything go wrong with your release?

**Comment by willholley** [comment]
@discostur I think this is blocked on merging #75 - when the CI issues are resolved we can look at merging/releasing.

**Comment by broomfn** [comment]
In case it's of any use to anyone, I used the following command to patch the ingress:

```
kubectl patch ingress/couch-couchdb --type json --patch '[{"op": "add", "path": "/spec/ingressClassName", value: "nginx" }]'
```
